name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      env:
        NEXT_PUBLIC_GEMINI_API_KEY: ${{ vars.NEXT_PUBLIC_GEMINI_API_KEY }}

    - name: Build project
      run: |
        npm run build
        touch ./out/.nojekyll
      env:
        NEXT_PUBLIC_GEMINI_API_KEY: ${{ vars.NEXT_PUBLIC_GEMINI_API_KEY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: out
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: true
        clean-exclude: |
          .nojekyll
